"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es" | "fr" | "zh"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "app.title": "MedTrack",
    "dashboard.title": "Dashboard",
    "prescriptions.title": "My Prescriptions",
    "prescriptions.status.filled": "Filled",
    "prescriptions.status.inProgress": "In Progress",
    "prescriptions.status.partial": "Partial",
    "prescriptions.status.readyForPickup": "Ready for Pickup",
    "prescriptions.pickup": "Pick Up",
    "prescriptions.refill": "Refill",
    "prescriptions.urgent": "Urgent",
    "prescriptions.nonUrgent": "Non-Urgent",
    "prescriptions.instructions": "Instructions",
    "prescriptions.sideEffects": "Side Effects",
    "prescriptions.allergies": "Allergies",
    "prescriptions.cost": "Cost",
    "prescriptions.insurance": "Insurance",
    "prescriptions.copay": "Copay",
    "prescriptions.retail": "Retail Price",
    "actions.consult": "Virtual Consultation",
    "actions.cost": "Cost Estimation",
    "actions.disposal": "Medication Disposal",
    "actions.queue": "Queue Status",
    "actions.accessibility": "Accessibility Options",
    "notifications.title": "Notifications",
    "notifications.email": "Email",
    "notifications.sms": "SMS",
    "notifications.push": "Push Notifications",
    "notifications.urgent": "Urgent Medications Only",
    "consultation.video": "Video Consultation",
    "consultation.chat": "Chat Consultation",
    "consultation.schedule": "Schedule Consultation",
    "consultation.history": "Consultation History",
    "queue.position": "Your Position",
    "queue.estimatedTime": "Estimated Wait Time",
    "queue.alert": "Alert When Ready",
    "disposal.title": "Medication Disposal",
    "disposal.instructions": "Disposal Instructions",
    "disposal.locations": "Disposal Locations",
    "disposal.reminders": "Disposal Reminders",
    "accessibility.curbside": "Curbside Pickup",
    "accessibility.assistance": "Request Assistance",
    "accessibility.map": "Accessibility Map",
    "accessibility.feedback": "Accessibility Feedback",
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.notifications": "Notification Preferences",
    "settings.privacy": "Privacy Settings",
    "settings.account": "Account Settings",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success",
    "common.minutes": "minutes",
    "common.hours": "hours",
    "common.days": "days",
  },
  es: {
    "app.title": "MedTrack",
    "dashboard.title": "Panel de Control",
    "prescriptions.title": "Mis Recetas",
    "prescriptions.status.filled": "Completada",
    "prescriptions.status.inProgress": "En Progreso",
    "prescriptions.status.partial": "Parcial",
    "prescriptions.status.readyForPickup": "Lista para Recoger",
    "prescriptions.pickup": "Recoger",
    "prescriptions.refill": "Rellenar",
    "prescriptions.urgent": "Urgente",
    "prescriptions.nonUrgent": "No Urgente",
    "prescriptions.instructions": "Instrucciones",
    "prescriptions.sideEffects": "Efectos Secundarios",
    "prescriptions.allergies": "Alergias",
    "prescriptions.cost": "Costo",
    "prescriptions.insurance": "Seguro",
    "prescriptions.copay": "Copago",
    "prescriptions.retail": "Precio Minorista",
    "actions.consult": "Consulta Virtual",
    "actions.cost": "Estimación de Costos",
    "actions.disposal": "Eliminación de Medicamentos",
    "actions.queue": "Estado de la Cola",
    "actions.accessibility": "Opciones de Accesibilidad",
    "notifications.title": "Notificaciones",
    "notifications.email": "Correo Electrónico",
    "notifications.sms": "SMS",
    "notifications.push": "Notificaciones Push",
    "notifications.urgent": "Solo Medicamentos Urgentes",
    "consultation.video": "Consulta por Video",
    "consultation.chat": "Consulta por Chat",
    "consultation.schedule": "Programar Consulta",
    "consultation.history": "Historial de Consultas",
    "queue.position": "Tu Posición",
    "queue.estimatedTime": "Tiempo Estimado de Espera",
    "queue.alert": "Alertar Cuando Esté Listo",
    "disposal.title": "Eliminación de Medicamentos",
    "disposal.instructions": "Instrucciones de Eliminación",
    "disposal.locations": "Ubicaciones de Eliminación",
    "disposal.reminders": "Recordatorios de Eliminación",
    "accessibility.curbside": "Recogida en la Acera",
    "accessibility.assistance": "Solicitar Asistencia",
    "accessibility.map": "Mapa de Accesibilidad",
    "accessibility.feedback": "Comentarios de Accesibilidad",
    "settings.title": "Configuración",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.notifications": "Preferencias de Notificación",
    "settings.privacy": "Configuración de Privacidad",
    "settings.account": "Configuración de la Cuenta",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.loading": "Cargando...",
    "common.error": "Ocurrió un error",
    "common.success": "Éxito",
    "common.minutes": "minutos",
    "common.hours": "horas",
    "common.days": "días",
  },
  fr: {
    "app.title": "MedTrack",
    "dashboard.title": "Tableau de Bord",
    "prescriptions.title": "Mes Ordonnances",
    "prescriptions.status.filled": "Remplie",
    "prescriptions.status.inProgress": "En Cours",
    "prescriptions.status.partial": "Partielle",
    "prescriptions.status.readyForPickup": "Prête à Récupérer",
    "prescriptions.pickup": "Récupérer",
    "prescriptions.refill": "Renouveler",
    "prescriptions.urgent": "Urgent",
    "prescriptions.nonUrgent": "Non Urgent",
    "prescriptions.instructions": "Instructions",
    "prescriptions.sideEffects": "Effets Secondaires",
    "prescriptions.allergies": "Allergies",
    "prescriptions.cost": "Coût",
    "prescriptions.insurance": "Assurance",
    "prescriptions.copay": "Quote-part",
    "prescriptions.retail": "Prix de Détail",
    "actions.consult": "Consultation Virtuelle",
    "actions.cost": "Estimation des Coûts",
    "actions.disposal": "Élimination des Médicaments",
    "actions.queue": "Statut de la File d'Attente",
    "actions.accessibility": "Options d'Accessibilité",
    "notifications.title": "Notifications",
    "notifications.email": "Email",
    "notifications.sms": "SMS",
    "notifications.push": "Notifications Push",
    "notifications.urgent": "Médicaments Urgents Uniquement",
    "consultation.video": "Consultation Vidéo",
    "consultation.chat": "Consultation par Chat",
    "consultation.schedule": "Planifier une Consultation",
    "consultation.history": "Historique des Consultations",
    "queue.position": "Votre Position",
    "queue.estimatedTime": "Temps d'Attente Estimé",
    "queue.alert": "Alerter Quand Prêt",
    "disposal.title": "Élimination des Médicaments",
    "disposal.instructions": "Instructions d'Élimination",
    "disposal.locations": "Lieux d'Élimination",
    "disposal.reminders": "Rappels d'Élimination",
    "accessibility.curbside": "Récupération en Bordure de Trottoir",
    "accessibility.assistance": "Demander de l'Assistance",
    "accessibility.map": "Carte d'Accessibilité",
    "accessibility.feedback": "Commentaires sur l'Accessibilité",
    "settings.title": "Paramètres",
    "settings.language": "Langue",
    "settings.theme": "Thème",
    "settings.notifications": "Préférences de Notification",
    "settings.privacy": "Paramètres de Confidentialité",
    "settings.account": "Paramètres du Compte",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.success": "Succès",
    "common.minutes": "minutes",
    "common.hours": "heures",
    "common.days": "jours",
  },
  zh: {
    "app.title": "MedTrack",
    "dashboard.title": "仪表板",
    "prescriptions.title": "我的处方",
    "prescriptions.status.filled": "已配药",
    "prescriptions.status.inProgress": "进行中",
    "prescriptions.status.partial": "部分完成",
    "prescriptions.status.readyForPickup": "可取药",
    "prescriptions.pickup": "取药",
    "prescriptions.refill": "续药",
    "prescriptions.urgent": "紧急",
    "prescriptions.nonUrgent": "非紧急",
    "prescriptions.instructions": "说明",
    "prescriptions.sideEffects": "副作用",
    "prescriptions.allergies": "过敏",
    "prescriptions.cost": "费用",
    "prescriptions.insurance": "保险",
    "prescriptions.copay": "自付额",
    "prescriptions.retail": "零售价",
    "actions.consult": "虚拟咨询",
    "actions.cost": "费用估算",
    "actions.disposal": "药物处置",
    "actions.queue": "队列状态",
    "actions.accessibility": "无障碍选项",
    "notifications.title": "通知",
    "notifications.email": "电子邮件",
    "notifications.sms": "短信",
    "notifications.push": "推送通知",
    "notifications.urgent": "仅紧急药物",
    "consultation.video": "视频咨询",
    "consultation.chat": "聊天咨询",
    "consultation.schedule": "安排咨询",
    "consultation.history": "咨询历史",
    "queue.position": "您的位置",
    "queue.estimatedTime": "预计等待时间",
    "queue.alert": "准备好时提醒",
    "disposal.title": "药物处置",
    "disposal.instructions": "处置说明",
    "disposal.locations": "处置地点",
    "disposal.reminders": "处置提醒",
    "accessibility.curbside": "路边取药",
    "accessibility.assistance": "请求协助",
    "accessibility.map": "无障碍地图",
    "accessibility.feedback": "无障碍反馈",
    "settings.title": "设置",
    "settings.language": "语言",
    "settings.theme": "主题",
    "settings.notifications": "通知首选项",
    "settings.privacy": "隐私设置",
    "settings.account": "账户设置",
    "common.save": "保存",
    "common.cancel": "取消",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.success": "成功",
    "common.minutes": "分钟",
    "common.hours": "小时",
    "common.days": "天",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  // Load language preference from localStorage on client side
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "es", "fr", "zh"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
